### ISSUE TITLE
可能跟版权相关的事情

### ISSUE THREAD

**Issue by ghost** [tjumyk/sdl-tutorial-cn#1]
无意间在原网站上发现[FAQ](http://lazyfoo.net/faq.php)里有这样一个问题：

Q: Can I port your code to Java/Perl/Python/C or **translate your tutorials to another language**?

A: **No.** From what I learned in my business law course, copyright law is sticky to say the least. If I do allow people to translate my tutorials who has rights to those translated tutorials is an complete mess. I'd rather just not deal with it. 

不知道你们如何看待这个事情？

**Comment by tjumyk** [comment]
Well, I knew that Q&A, you really have a pair of sharp eyes...

But in my opinion, our translation project is an open source project, which means everyone can get it and edit it, so all the people own and share this translation, it's not mine, yours, or someone else's. We read it, we understand it, we use it, and even we improve it, so no personal interests or even commercial interests exist here.

So, any issues about the copyright may make no sense. And I think the original author should respect this kind of public-walfare project.

At last, if you're still willing to 'fight for the copyright' or want to use the 'law' to say something, I will say that sinse Github is an American company, I obey the American law. And you may see even Google has met some issues about the copyright, just like Google Books, and the current law system cannot definitely judge the similar cases. 

However, while Google being an enterprise company, wanting to make more money, we are only programmers who desire to share our thoughts and writings. So we are at least not doing bad things, though we admit that the quality or completeness may be unsatisfactory now. 

We hope we can get support from the original author, and everyone like you can understand and respect what we've done. It will be appreciated for you to help us improve this translation with any means.

Thank you.

**Comment by ghost** [comment]
其实，我并不是说一定要搞版权之类的事情。。。
其实，开源也是讲究版权的。。。扯远了

曾经看到过有一些原作者，可能对开源有着不太相同的看法
并不是说，你开源他就会觉得没问题的，而且他好像也没有标注说遵守CC许可协议之类的

我想说的只是，你们有没有联系过原作者？
或者告诉过他，这里搞了一个翻译的版本，并遵守CC许可协议，这样可不可以，之类的。。。
我只是希望，大家费心费力搞了这么一个好的翻译版本，最后不要发生被原作者否定之类的事情。。。
也可以认为是我想多了

**Comment by mountain19770101** [comment]
其实一个人如果选择SDL，英文就不是障碍了
