### ISSUE TITLE
我的系统是ubuntu12.0.4，下载了SDL源码编译安装的，然后编译示例程序没有问题，运行程序却出现如下问题

### ISSUE THREAD

**Issue by chain78** [tjumyk/sdl-tutorial-cn#2]
X error of failed request:BadRequest(invalid request code or no such operation)
Major opcode of failed request:153(G LX)
Minor opcode of failed request:19(X_GLXQueryServerString)
Serial number of failed request:72
Current serial number in output stream:72

**Comment by ghost** [comment]
哈喽，从你给出的信息来看想要分析问题的原因还有些困难（也可能是我个人的技术不过硬(=ﾟωﾟ)ﾉ）。

或许提供更多的信息会帮助大家更好地分析问题。例如你的显卡型号、显卡驱动的安装情况、是否手动更改了X Server的配置文件、编译安装SDL时的选项等等。另外，你使用其他SDL的程序是否出现问题呢？

西瓜玩偶

**Comment by chain78** [comment]
VGA compatible controller:Advanced Micro Devices,Inc.[AMD/ATI] RV620/M82 [Mobility Radeon HD 3450/3470](pro-if 00 [VGA controller])

我一开始装了sdl1.2,用的apt-get，命令:
apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
测试过，程序没有任何问题

后来从官网下载了SDL2.0源码，解压，安装:
./configure 
make
make install
没有问题，动态链接库在/usr/local/lib下，在/etc/ld.so.conf文件中添加此路径

编译程序没有问题，运行出错

**Comment by ghost** [comment]
嗨，

从你的描述来看，问题有可能出在运行时的SDL版本与编译SDL时的版本不同造成的。以我的经验来看，SDL1.2与SDL2.0并不兼容。起先如果编译SDL1.2成功，而后来SDL2.0编译安装之后却出问题，可能是2.0的运行库覆盖了1.2的运行库。

可以做一下实验，还原使用1.2版本的库之后确认运行是否成功，再根据运行的结果考虑解决的方案。

西瓜玩偶
